### ISSUE TITLE
Getting Avro error while trying to load data from EMR spark dataframe to redshift table.

### ISSUE THREAD

**Issue by manisha803** [databricks/spark-redshift#222] opened 2016-06-27 21:10 UTC
16/06/27 17:00:14 ERROR InsertIntoHadoopFsRelation: Aborting task.
java.lang.IncompatibleClassChangeError: Found interface org.apache.hadoop.mapreduce.TaskAttemptContext, but class was expected
	at org.apache.avro.mapreduce.AvroKeyOutputFormat.getRecordWriter(AvroKeyOutputFormat.java:85)
	at com.databricks.spark.avro.AvroOutputWriter.<init>(AvroOutputWriter.scala:82)
	at com.databricks.spark.avro.AvroOutputWriterFactory.newInstance(AvroOutputWriterFactory.scala:31)
	at org.apache.spark.sql.sources.DefaultWriterContainer.initWriters(commands.scala:470)
	at org.apache.spark.sql.sources.BaseWriterContainer.executorSideSetup(commands.scala:360)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation.org$apache$spark$sql$sources$InsertIntoHadoopFsRelation$$writeRows$1(commands.scala:172)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation$$anonfun$insert$1.apply(commands.scala:160)
	at org.apache.spark.sql.sources.InsertIntoHadoopFsRelation$$anonfun$insert$1.apply(commands.scala:160)
	at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:63)
	at org.apache.spark.scheduler.Task.run(Task.scala:70)
	at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:213)

**Comment by JoshRosen** [comment] 2016-06-27 22:03
This looks like a duplicate of #180 and is likely a problem with dependency conflicts in your environment.

**Comment by manisha803** [comment] 2016-06-27 22:39
I am using EMR 4.6.0 and spark 1.6.1. #180 is for the older version of the spark.

**Comment by JoshRosen** [comment] 2016-06-27 22:40
Which versions of `spark-redshift`, `spark-avro`, and `avro-mapred` are you using?

**Comment by manisha803** [comment] 2016-06-27 22:42
Hello,

I am using following dependency.
<dependency>
    <groupId>com.databricks</groupId>
    <artifactId>spark-avro_2.10</artifactId>
    <version>2.0.1</version>
      </dependency>
      <dependency>
    <groupId>org.apache.avro</groupId>
    <artifactId>avro-mapred</artifactId>
    <classifier>hadoop2</classifier>
    <version>1.7.7</version>

      <dependency>
    <groupId>com.databricks</groupId>
    <artifactId>spark-redshift_2.10</artifactId>
    <version>0.6.0</version>

Thanks
Manisha,

**Comment by JoshRosen** [comment] 2016-09-20 23:16
Please give this a try using the 1.0.1 release of this library and re-open if this still an issue.

**Closed by JoshRosen** 2016-09-20 23:16 UTC
