### ISSUE TITLE
UNLOAD where policy on S3 requires all objects to be encrypted ( Server Side Encryption)

### ISSUE THREAD

**Issue by NeilJonkers** [databricks/spark-redshift#309] opened 2016-12-05 09:15 UTC
Documenting known issue to help other folks coming across the same issue:
5 December 2016

In S3 we can apply a bucket policy that requires all objects written to the S3 bucket to be encrypted using Server Side Encryption.
http://docs.aws.amazon.com/AmazonS3/latest/dev/UsingServerSideEncryption.html

When we call UNLOAD from Redshift, we specify the MANIFEST file:
[RedshiftRelation.scala](https://github.com/databricks/spark-redshift/blob/1092c7cd03bb751ba4e93b92cd7e04cffff10eb0/src/main/scala/com/databricks/spark/redshift/RedshiftRelation.scala#L196)

Small issue at the moment is, {I heard Josh mention this on other issues as well}, that the MANIFEST file created by Redshift is not server side encrypted. This results in the UNLOAD fail when the S3 bucket has the SSE as a requirement in the bucket policy.

The overall issue is for Redshift to fix, i.e. Redshift should encrypt the MANIFEST file.

From my inspection of the code, we always include the MANIFEST option when calling UNLOAD.

**Comment by JoshRosen** [comment] 2016-12-05 20:23
Until S3 offers strongly-consistent LIST operations we'll need to use `MANIFEST` to avoid silent data loss due to eventual consistency. Thus I don't think it's a good idea to omit `MANIFEST` here.

Does Redshift allow you to write the manifest to a different bucket than the data itself? If so, we could consider adding a configuration to allow this so that the secret-data-free manifest file can be written to a bucket with fewer policy restrictions while the data is written to the encryption-only bucket.

**Comment by NeilJonkers** [comment] 2016-12-05 20:52
Thanks Josh.

I will confirm this and report back.

**Comment by NeilJonkers** [comment] 2016-12-06 09:38
Seems Redshift does not have a feature to place the MANIFEST file in a different S3 bucket.

**Comment by JoshRosen** [comment] 2016-12-06 17:56
Ah, bummer. If you do end up reaching out to either Amazon support or the Redshift team to discuss this then please link this issue so that they can chime in directly here.

**Comment by JoshRosen** [comment] 2017-02-24 01:51
Over at https://github.com/databricks/spark-redshift/issues/321#issuecomment-276505703, @svadakattu reported another occurrence of this problem.

I took another read through the Amazon Redshift docs to try to corroborate the claim that Redshift's MANIFEST is not encrypted when written by UNLOAD. I believe this claim originates from https://docs.aws.amazon.com/redshift/latest/dg/t_unloading_encrypted_files.html, a page discussing the `ENCRYPTED` option of the `UNLOAD` command. This page clearly states that the manifest will not be encrypted but I think this is a conditional statement applying only when `ENCRYPTED` is specified.

According to https://docs.aws.amazon.com/redshift/latest/dg/r_UNLOAD.html, it sounds like UNLOAD is supposed to write all data using `sse-s3` by default and there's no exemption specifically saying that MANIFEST won't be encrypted.

If this interpretation is correct and we're using correctly-formed bucket policies but still seeing failures in writing the manifest then it sounds like this could be a Redshift bug which we'd need to escalate to Amazon.

I've tried to reproduce this error in a testing/staging environment using a bucket policy provided by a customer but have been unable to trigger it. It's possible that Amazon may have fixed a bug here in the most recent Redshift release, which might explain why I can't reproduce it.

@NeilJonkers @svadakattu, it would be useful to know whether either of you are able to reproduce this today using the latest Redshift release. If so, it would be great if you could share your bucket policies with me (my email is in my GItHub profile).

**Comment by NeilJonkers** [comment] 2017-02-28 17:54
Correct Josh the feature has recently been added: [ 9 February 2017 UNLOAD support SSE with encrypted MANIFEST ](http://docs.aws.amazon.com/redshift/latest/dg/doc-history.html)

**Comment by svadakattu** [comment] 2017-02-28 19:32
@JoshRosen The issue seems fixed now with the latest release. I am yet to test the connector but the plain UNLOAD worked now

**Comment by granturing** [comment] 2017-03-01 05:40
@NeilJonkers while I agree the issue seems to be fixed, I don't see it explicitly listed in the release notes for Feb 9, 2017?

**Comment by JoshRosen** [comment] 2017-03-03 19:06
It's not mentioned in https://aws.amazon.com/releasenotes/Amazon-Redshift/1967974092607164 either, which are the actual release notes for that version. 😦 

I'm going to go ahead and close this issue since it sounds like everything is fixed. Support for writes will be tracked in #321.

**Closed by JoshRosen** 2017-03-03 19:06 UTC
