### ISSUE TITLE
java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter

### ISSUE THREAD

**Issue by hafizmujadid** [databricks/spark-redshift#129] opened 2015-11-25 10:27 UTC
Hi1

I am using spark-redshift to save dataframe into redshift but facing following exception.

```
java.lang.NoSuchMethodError: org.apache.avro.generic.GenericData.createDatumWriter(Lorg/apache/avro/Schema;)Lorg/apache/avro/io/DatumWriter;
        at org.apache.avro.mapreduce.AvroKeyRecordWriter.<init>(AvroKeyRecordWriter.java:55)
        at org.apache.avro.mapreduce.AvroKeyOutputFormat$RecordWriterFactory.create(AvroKeyOutputFormat.java:79)
        at org.apache.avro.mapreduce.AvroKeyOutputFormat.getRecordWriter(AvroKeyOutputFormat.java:105)
        at com.databricks.spark.avro.AvroOutputWriter.<init>(AvroOutputWriter.scala:82)
        at com.databricks.spark.avro.AvroOutputWriterFactory.newInstance(AvroOutputWriterFactory.scala:31)
        at org.apache.spark.sql.execution.datasources.DefaultWriterContainer.writeRows(WriterContainer.scala:234)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
        at org.apache.spark.sql.execution.datasources.InsertIntoHadoopFsRelation$$anonfun$run$1$$anonfun$apply$mcV$sp$3.apply(InsertIntoHadoopFsRelation.scala:150)
        at org.apache.spark.scheduler.ResultTask.runTask(ResultTask.scala:66)
        at org.apache.spark.scheduler.Task.run(Task.scala:88)
        at org.apache.spark.executor.Executor$TaskRunner.run(Executor.scala:214)
        at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
        at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
        at java.lang.Thread.run(Thread.java:745)
```

**Comment by JoshRosen** [comment] 2015-11-25 17:14
I suspect that this is caused by an older version of Avro being used. Over at the `spark-avro` repo, https://github.com/databricks/spark-avro/issues/91 discusses how this problem can occur on EMR, where the older version of Avro that's provided by the EMR environment takes precedence. If you happen to be running on EMR, check out the bottom of that thread for a workaround / fix.

**Comment by hafizmujadid** [comment] 2015-11-27 07:09
i am using spark-avro latest version but i am facing same issue. Spark-redshift is really pissing me off :(

**Comment by JoshRosen** [comment] 2015-11-30 19:54
If you read the `spark-avro` issue that I linked upthread, you'll see that the problem is due to the versions of the `avro-mapred` library that is provided by your runtime environment, which is independent of the `spark-avro` version that you're using. In order to debug this issue, you'll need to figure out where `avro-mapred` is coming from and see which version is being used.

If it was me, I'd use `Class.forName` and the steps described in https://stackoverflow.com/questions/1983839/determine-which-jar-file-a-class-is-from to figure out which JARs `org.apache.avro.mapreduce.AvroKeyRecordWriter` and `org.apache.avro.generic.GenericData` are being loaded from; once you know where the dependencies are coming from, we should be able to figure out how to ensure that a newer version of Avro gets used.

**Comment by hafizmujadid** [comment] 2015-11-30 19:56
thanks Josh :) i will try your solution

On Tue, Dec 1, 2015 at 12:54 AM, Josh Rosen <notifications@github.com>
wrote:

> If you read the spark-avro issue that I linked upthread, you'll see that
> the problem is due to the versions of the avro-mapred library that is
> provided by your runtime environment, which is independent of the
> spark-avro version that you're using. In order to debug this issue,
> you'll need to figure out where avro-mapred is coming from and see which
> version is being used.
>
> If it was me, I'd use Class.forName and the steps described in
> https://stackoverflow.com/questions/1983839/determine-which-jar-file-a-class-is-from
> to figure out which JARs org.apache.avro.mapreduce.AvroKeyRecordWriter
> and org.apache.avro.generic.GenericData are being loaded from; once you
> know where the dependencies are coming from, we should be able to figure
> out how to ensure that a newer version of Avro gets used.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/databricks/spark-redshift/issues/129#issuecomment-160740317>
> .
>



-- 
Regards: HAFIZ MUJADID

**Comment by JoshRosen** [comment] 2015-12-15 19:49
I'm going to close this issue as 'not a `spark-redshift` issue', since I don't think that there's anything actionable here from our side. Feel free to update this thread if you'd still like some help in debugging your environment issue.

**Closed by JoshRosen** 2015-12-15 19:49 UTC

**Comment by WillSidebottom** [comment] 2016-05-19 17:08
@hafizmujadid Did you ever get this issue fixed? I'm running into the same problem, just trying to save a simple DataFrame into aws Redshift.
-Thanks!

**Comment by hafizmujadid** [comment] 2016-05-20 09:51
No, I could not get this issue fixed and left the effort to use spark_redshift

**Comment by WillSidebottom** [comment] 2016-05-22 19:45
OK, are you still writing data to Redshift from spark? If so, how are you doing it? 
Thanks again!

**Comment by hafizmujadid** [comment] 2016-05-23 04:49
There are multiple options to do so.

1. you can use same approach as Spark-RedShift and save your data from in
S3 bucket and then run copy command using redshift jdbc driver.

2. Use SaveAsHadoopDataSet as in following code

        val dbUrl = "jdbc:postgresql://" + endpoint + ":" + port + "/" +
database + "?user=" + username + "&password=" + password
        val records = df.map(row => (TableRow(row.toString, columnTypes),
null))
        val jobConf = new JobConf()
DBConfiguration.configureDB(jobConf, "org.postgresql.Driver", dbUrl,
username, password)
DBOutputFormat.setOutput(jobConf, table, columns: _*)
records.saveAsHadoopDataset(jobConf)

On Mon, May 23, 2016 at 12:46 AM, WillSidebottom <notifications@github.com>
wrote:

> OK, are you still writing data to Redshift from spark? If so, how are you
> doing it?
> Thanks again!
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub
> <https://github.com/databricks/spark-redshift/issues/129#issuecomment-220851987>
>



-- 
Regards: HAFIZ MUJADID
