### ISSUE TITLE
S3 Bucket does not exist error

### ISSUE THREAD

**Issue by gushishii** [databricks/spark-redshift#181] opened 2016-02-23 01:31 UTC
About 2-3 weeks ago, I was able to run spark and have it write to the exact same bucket. However when I run the spark job today, i got the following message.

16/02/23 01:25:51 ERROR Utils$: The S3 bucket nysdoh.hci3.kpmg.two does not exist
16/02/23 01:25:51 ERROR Utils$: The S3 bucket nysdoh.hci3.kpmg.two does not exist
....
16/02/23 01:25:51 ERROR ApplicationMaster: User class threw exception: java.sql.SQLException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;
java.sql.SQLException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;
	at com.amazon.redshift.client.messages.inbound.ErrorResponse.toErrorException(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleErrorResponse(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getReadyForQuery(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.handleMessage(Unknown Source)
	at com.amazon.jdbc.communications.InboundMessagesPipeline.getNextMessageOfClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.doMoveToNextClass(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getReadyForQuery(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.client.PGMessagingContext.getOperationMetadata(Unknown Source)
	at com.amazon.redshift.dataengine.PGExecutionResults.<init>(Unknown Source)
	at com.amazon.redshift.dataengine.PGAbstractQueryExecutor.getResults(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.executeWithParams(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:122)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$executeInterruptibly$1.apply(RedshiftJDBCWrapper.scala:122)
	at com.databricks.spark.redshift.JDBCWrapper$$anonfun$2.apply(RedshiftJDBCWrapper.scala:140)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.liftedTree1$1(Future.scala:24)
	at scala.concurrent.impl.Future$PromiseCompletingRunnable.run(Future.scala:24)
	at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1145)
	at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:615)
Caused by: com.amazon.support.exceptions.ErrorException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;
	... 27 more
16/02/23 01:25:51 INFO ApplicationMaster: Final app status: FAILED, exitCode: 15, (reason: User class threw exception: java.sql.SQLException: [Amazon](500310) Invalid operation: Specified types or functions (one per INFO message) not supported on Redshift tables.;)

Thank you!

**Comment by JoshRosen** [comment] 2016-02-23 01:33
Can you post more of the stacktrace? My first suspicion is that this is a duplicate of #171.

**Comment by JoshRosen** [comment] 2016-02-23 01:36
I think the problem here is `Specified types or functions (one per INFO message) not supported on Redshift tables`, which sounds like a Redshift problem. I think that you'll have to look at your Redshift error logs in order to figure out which SQL function is triggering this. You might be able to figure this out by looking at the log messages which report the actual queries which are issued against Redshift.

**Comment by gushishii** [comment] 2016-02-23 01:39
So this is what I did:
I first did a read and have the result saved to a folder. Spark executes that fine but I don't see the temp file got created the folder.
Then I added a write command, re-execute the job, Spark started to complain that it cannot find the folder/file.
Thank you for your time!

**Comment by gushishii** [comment] 2016-02-23 01:41
2-3 weeks ago, when I do a df.read, I see the temp file got created and stored in S3. Are they supposed to be deleted now?

**Comment by JoshRosen** [comment] 2016-02-23 01:56
Did you configure a bucket lifecycle policy to delete the temporary files from S3?

**Comment by gushishii** [comment] 2016-02-23 02:16
No I didn't change the lifecycle.

**Comment by JoshRosen** [comment] 2016-02-23 02:17
> I first did a read and have the result saved to a folder.

Do you mean that you explicitly saved the result of a Redshift read, e.g. with `someDf.write.someFormat`?

**Comment by gushishii** [comment] 2016-02-23 17:58
I didn't explicitly save the read results. What i meant was that after spark got executed I saw a temp file got created in S3. But I don't see the temp files anymore. 
The following is the command I used.

		val df = sqlContext.read
		    .format("com.databricks.spark.redshift") 
		    .option("url", jdbcURL) 
		    .option("query", "select * from provider limit 10") 
		    .option("tempdir", tempS3Dir) 
		    .load()

		df.registerTempTable("pg_amproc")

		sqlContext.sql("SELECT * FROM pg_amproc")
			.write.format("com.databricks.spark.redshift")
			.option("url", jdbcURL)
			.option("tempdir", tempS3Dir) 
			.option("dbtable", "pn1") 
			.mode(SaveMode.Overwrite)
			.save()

**Comment by JoshRosen** [comment] 2016-02-23 18:19
Sounds like those temp files are being deleted somehow. If you don't have a bucket lifecycle policy that's deleting them then some other process must be doing it. `spark-redshift` will never reuse unload paths / directories and will never delete those files by itself.

**Comment by JoshRosen** [comment] 2016-03-21 19:37
Closing as stale for now. Please re-open if you have additional information.

**Closed by JoshRosen** 2016-03-21 19:37 UTC

**Comment by gushishii** [comment] 2016-04-08 18:25
Sorry for the late response. It's working again. i haven't changed the code nor s3 configuration tho.. mystery..

**Comment by jomach** [comment] 2016-04-29 09:28
+1
