### ISSUE TITLE
Load large-size table from RS

### ISSUE THREAD

**Issue by gracezxl** [databricks/spark-redshift#192] opened 2016-03-17 10:03 UTC
Hi 

I met a problem in loading a large-size(97G) table into my hdfs. I learned the code from Readme.md, as show in the following. If I set my spark conf as master = "local[2]", the program get error saying that 'Mkdirs failed to create temporary file in hdfs', but it works if I set master = "local[1]". Does it mean that I can not load large-size table using multiple threads? The error does not happen when I load a small-size table.
After I run successfully, I met the other problem. The program does not stop, seems the load process takes very long time. Is it possible to load in a compressed way?

Is there any good method to load large-size table into my server?

# Read data from a table
df = sql_context.read \
    .format("com.databricks.spark.redshift") \
    .option("url", "jdbc:redshift://redshifthost:5439/database?user=username&password=pass") \
    .option("dbtable", "my_table") \
    .option("tempdir", "s3n://path/for/temp/data") \
    .load()

Thank you!

**Comment by JoshRosen** [comment] 2016-03-17 18:47
Can you post the stacktrace of the error? I'm not sure whether the "'Mkdirs failed to create temporary file in hdfs" message is a red-herring.

**Comment by JoshRosen** [comment] 2016-03-21 19:35
Closing as "cannot reproduce / underspecified for now." Please update and re-open when you have more information.

**Closed by JoshRosen** 2016-03-21 19:35 UTC
