### ISSUE TITLE
AWS config issues (python)

### ISSUE THREAD

**Issue by TELSER1** [databricks/spark-redshift#89] opened 2015-09-14 23:47 UTC
I've been working on getting my aws credentials properly set up to read/write, and encountered some issues:

1.) The given example has aws access being configured by sc.hadoopConfig.set("fs.s3n.awsAccessKeyId", "YOUR_KEY_ID"),etc ; there is no hadoopConfig method for the pyspark context.  It seems to be possible to pass a config file to hadoopFile, but this seems specific to whatever file you're pointing it at.

2.)  s3n://ACCESSKEY:SECRETKEY@bucket/path/to/temp/dir works absolutely fine when reading from redshift, but throws
<code>java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL</code>

when writing the dataframe back to redshift.

Both work fine if I define access/secret key environment variables before launching the shell, although the write throws 'invalid AVRO file found', probably because the column names contain _, as per https://github.com/databricks/spark-redshift/issues/84 .

**Comment by JoshRosen** [comment] 2015-09-15 00:05
@TELSER1, I realized that I was a bit ambiguous in #84: underscores _should_ work, as should alphanumeric characters; it's other characters that are the problem. Can you share more of the stacktrace / info RE: the "invalid AVRO file found" error that you saw?

**Comment by TELSER1** [comment] 2015-09-15 00:34
<code>traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/lib/spark/python/pyspark/sql/readwriter.py", line 302, in save
    self._jwrite.save()
  File "/usr/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/java_gateway.py", line 538, in __call__
  File "/usr/lib/spark/python/lib/py4j-0.8.2.1-src.zip/py4j/protocol.py", line 300, in get_return_value
py4j.protocol.Py4JJavaError: An error occurred while calling o43.save.
: java.sql.SQLException: 
Error (code 1216) while loading data into Redshift: "Invalid AVRO file found. Unexpected end of AVRO file."
Table name: sparktest2
Column name: 
Column type: 
Raw line: Obj...avro.codec</code>

<code>snappy.avro.schema.0{MYCOLUMNS}</code>

<code>
	at com.databricks.spark.redshift.RedshiftWriter.com$databricks$spark$redshift$RedshiftWriter$$doRedshiftLoad(RedshiftWriter.scala:170)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:288)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:104)
	at org.apache.spark.sql.sources.ResolvedDataSource$.apply(ddl.scala:309)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:144)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:379)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:207)
	at java.lang.Thread.run(Thread.java:745)
Caused by: java.sql.SQLException: [Amazon](500310) Invalid operation: Load into table 'sparktest2' failed.  Check 'stl_load_errors' system table for details.;</code>

**Comment by JoshRosen** [comment] 2015-09-15 01:44
@TELSER1, in order to help me reproduce this bug it would be helpful if you could share some more information about the schema of the table that you're trying to save. If you don't feel comfortable sharing these details publicly, feel free to email me at joshrosen@databricks.com.

**Comment by TELSER1** [comment] 2015-09-15 18:06
Sent.

**Comment by JoshRosen** [comment] 2015-09-30 21:12
@TELSER1, I now have a patch open to fix the "Invalid AVRO file found. Unexpected end of AVRO file" error that you saw: #96.

As far as the rest of this issue is concerned, I'm going to leave this issue open so that we remember to follow up on updating the Python docs to include a workaround for setting Hadoop configuration properties.

As far as the `s3n://` credentials issue is concerned, do your keys happen to contain backslashes?

**Comment by TELSER1** [comment] 2015-09-30 22:00
No, they do not contain any backslashes.

**Comment by TELSER1** [comment] 2015-09-30 22:06
No, my keys are backslash free.

**Comment by JoshRosen** [comment] 2015-10-21 08:46
@TELSER1, I spent a bit of time trying to reproduce this in various environments and haven't been able to trigger the problem that you reported with the `s3n://` credentials. If you happen to still have it, could you share the full stracktrace of that error to see exactly where we're failing to get the credentials?

**Comment by JoshRosen** [comment] 2015-10-21 09:06
Actually it looks like this has been fixed in 0.5.1, which is why I couldn't reproduce it.

For the record, here's a complete stacktrace:

```python
: java.lang.IllegalArgumentException: AWS Access Key ID and Secret Access Key must be specified as the username or password (respectively) of a s3n URL, or by setting the fs.s3n.awsAccessKeyId or fs.s3n.awsSecretAccessKey properties (respectively).
	at org.apache.hadoop.fs.s3.S3Credentials.initialize(S3Credentials.java:70)
	at org.apache.hadoop.fs.s3native.Jets3tNativeFileSystemStore.initialize(Jets3tNativeFileSystemStore.java:55)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invokeMethod(RetryInvocationHandler.java:186)
	at org.apache.hadoop.io.retry.RetryInvocationHandler.invoke(RetryInvocationHandler.java:102)
	at org.apache.hadoop.fs.s3native.$Proxy18.initialize(Unknown Source)
	at org.apache.hadoop.fs.s3native.NativeS3FileSystem.initialize(NativeS3FileSystem.java:272)
	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:2433)
	at org.apache.hadoop.fs.FileSystem.access$200(FileSystem.java:88)
	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:2467)
	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:2449)
	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:367)
	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:287)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:206)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:139)
	at com.databricks.spark.redshift.RedshiftWriter.com$databricks$spark$redshift$RedshiftWriter$$unloadData(RedshiftWriter.scala:257)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:287)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:104)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:197)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:148)
	at sun.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
	at sun.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:57)
	at sun.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
	at java.lang.reflect.Method.invoke(Method.java:606)
	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:231)
	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:381)
	at py4j.Gateway.invoke(Gateway.java:259)
	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:133)
	at py4j.commands.CallCommand.execute(CallCommand.java:79)
	at py4j.GatewayConnection.run(GatewayConnection.java:209)
	at java.lang.Thread.run(Thread.java:745)
```

Unfortunately, the stack trace itself was elided and I had to modify PySpark SQL to show it:
https://github.com/apache/spark/blob/5cdea7d1e54e751f928876ead33fc01e7e2f3437/python/pyspark/sql/utils.py#L41. @viirya, @davies, @rxin, it looks like this exception-masking behavior was an unfortunately consequence of https://github.com/apache/spark/pull/7497 and it made this issue harder to debug. We should consider either reverting that patch in Spark or making it apply more narrowly to certain internal Spark exceptions and not exceptions that originate from third-party code.

Digging into the 0.5.0 code, it looks like the problem was that the original implementation of `Utils.joinUrls` might not have preserved credentials: https://github.com/databricks/spark-redshift/blame/v0.5.0/src/main/scala/com/databricks/spark/redshift/Utils.scala#L47:

```scala
scala> joinUrls("s3n://ACCESSKEY:SECRETKEY@bucket/path/to/temp/dir", "subdir")
res4: String = s3n://bucket/path/to/temp/dir/subdir/
```

Note that this implementation also had other bugs, such as not working on Windows, and was replaced in 0.5.1 in #93. Therefore, it's safe to mark this issue as fixed in 0.5.1, although I'd like to followup and write a targeted regression test for this.

**Comment by JoshRosen** [comment] 2015-10-21 21:20
I wrote an integration test and discovered that there actually still is a bug here, as well as some inaccuracies in the documentation, so I'm going to submit a PR to fix this.

**Comment by TELSER1** [comment] 2015-10-21 21:46
Do you still need the full stack trace?

**Comment by JoshRosen** [comment] 2015-10-21 21:47
@TELSER1, not anymore; I managed to come up with a full reproduction on my own.

**Closed** 2015-10-22 02:23 UTC
Labels: bug, documentation
