### ISSUE TITLE
[Amazon](500150) Error setting/closing connection: Not Connected

### ISSUE THREAD

**Issue by jelez** [databricks/spark-redshift#148] opened 2016-01-05 05:37 UTC
I get the following error when running a test job from my PC. I have connectivity to the redshift cluster because at the same time I am running Aginity workbench session.

Any idea what settings can be tweaked to avoid it? it may be a timeout...

```
16/01/04 21:17:48 INFO RedshiftWriter: CREATE TABLE IF NOT EXISTS "staging"."messages_20160104_205059" ("message_id" ...
Exception in thread "main" java.sql.SQLException: [Amazon](500150) Error setting/closing connection: Not Connected.
	at com.amazon.redshift.client.PGClient.isConnected(Unknown Source)
	at com.amazon.redshift.client.PGClient.reprepareStatement(Unknown Source)
	at com.amazon.redshift.dataengine.PGAbstractQueryExecutor.pushMappedParamTypes(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.updateParameterMetadata(Unknown Source)
	at com.amazon.jdbc.common.SPreparedStatement.execute(Unknown Source)
	at com.databricks.spark.redshift.RedshiftWriter.com$databricks$spark$redshift$RedshiftWriter$$doRedshiftLoad(RedshiftWriter.scala:163)
	at com.databricks.spark.redshift.RedshiftWriter.saveToRedshift(RedshiftWriter.scala:381)
	at com.databricks.spark.redshift.DefaultSource.createRelation(DefaultSource.scala:106)
	at org.apache.spark.sql.execution.datasources.ResolvedDataSource$.apply(ResolvedDataSource.scala:170)
	at org.apache.spark.sql.DataFrameWriter.save(DataFrameWriter.scala:146)
	at com.amazonaws.proserve.jelez.spark.kinesis2redshift.FlattenJsonToRedshiftAndS3Batch$.main(FlattenJsonToRedshiftAndS3Batch.scala:183)
Caused by: com.amazon.support.exceptions.GeneralException: [Amazon](500150) Error setting/closing connection: Not Connected.
	... 11 more
```

**Comment by JoshRosen** [comment] 2016-01-05 07:53
Did you try Googling the exception? When I searched for "[Amazon](500150) Error setting/closing connection: Not Connected.", in quotes, I found two relevant links:

- http://wiki.pentaho.com/display/analysis/PA_CR_PA-3.9.0.0-RC1_redshift_08.00.0002_RedshiftJDBC-1.0.13.1313
- https://sagebionetworks.jira.com/browse/BRIDGE-559

The second link suggests that this could be caused by MTU issues.

Is the "Aginity workbench session" initiating the JDBC connection from your PC or is it using some sort of client-server architecture where the actual connection is being established from a different machine?

In either case, I'm not sure that this is an issue with `spark-redshift` itself, so I'm going to resolve this as "not-a-spark-redshift" issue and suggest that you contact Amazon support to troubleshoot this connection  issue.

**Other readers:** if you also see this exception, don't hesitate to bump this thread with a "me, too!". I'm only closing this issue to avoid cluttering the open issues queue with things that aren't actionable from my end.

**Closed by JoshRosen** 2016-01-05 07:53 UTC

**Comment by biolearning** [comment] 2016-08-26 09:05
me, too!
I am using 1.1.6 Redshift driver in JasperServer 6.01 to connect Redshift.
Occasionally, JasperServer will error with '[Amazon](500150) Error setting/closing connection: Not Connected.', we tried to reproduce this issue but failed, do not know how it can happen. It can be recovered by JapserServer restartup.

**Comment by Regalcom** [comment] 2016-12-07 16:11
This worked for me....
1. Sign-in into AWS Console
2. Go into EC2 Management Console
3. On the left navigation pane, look for Network & Security header and click on Security Groups.
4. Notice the row with "Default" in the Group Name's column. Click that. Then select the Inbound tab, and click Edit.
5. Add Rule: Type=Redshift, Source=MyIP. (auto-fill)
6. Save it.
7. Try to connect again from within SQLWorkbench/J. Feel good!

**Comment by triptimahakul** [comment] 2016-12-28 15:22
I tried the steps above  but it still doesnt work. What am i missing?

**Comment by adzsroka** [comment] 2017-01-04 09:41
I've also been having this issue. Assigned an IAM role that had full permissions and using that hadn't worked. Looking at the flow log on AWS it seems that the outgoing communication from Databricks to Redshift is going to the correct location and is accepted, but no response is given - causing it to timeout as it waits.

**Comment by AlexRuizE** [comment] 2017-01-04 22:33
I have a similar issue as @adzsroka. Have assigned the proper IAM role that works fine locally to extract data from Redshift via Spark. I spun up a cluster in Databricks a few hours ago, loaded "RedshiftJDBC41-1.1.7.1007", getting the timeout.

**Comment by pigate** [comment] 2017-02-21 00:51
I'm having a similar issue in cluster mode, using spark-redshift 2.0.1. Works fine on simple queries, but on more complicated queries, after 2 hours (and we see the temp directories being written to in s3) we get this timeout.

**Comment by amitdubey766** [comment] 2017-04-10 11:20
@pigate is right, I have a the same issue, its not working on complicated queries.

**Comment by ericson-cepeda** [comment] 2017-04-12 18:16
I was experiencing the same issue, when queries take more than 2 hours. Found an interesting post: https://kb.informatica.com/solution/23/Pages/57/485601.aspx

sudo /sbin/sysctl -w net.ipv4.tcp_keepalive_time=200 net.ipv4.tcp_keepalive_intvl=200 net.ipv4.tcp_keepalive_probes=5

It works for me now.

**Comment by gabi-lee** [comment] 2017-08-12 18:08
Happened to me because I selected "No" in the "Publicly accessible" option.
Go to the instance details and choose "Modify"

**Comment by whitsonk** [comment] 2017-09-07 09:00
I had the same problem as gabi-lee. I selected "No" in the "Publicly accessible" option. Consequently, despite having inbound security wide open, I was unable to connect.
"[Amazon](500150) Error setting/closing connection"
To fix, choose your redshift cluster and then click the "cluster" drop down.
Select modify and then change publicly accessible. 
It took about a minute or so to take effect.

**Comment by aloksaxena93** [comment] 2017-11-01 21:11
The recommendation posted above by Regalcom worked for me. Thanks!

**Comment by ghost** [comment] 2018-01-05 07:36
Here's what worked for me.
1. On the Redshift dashboard, on the left panel, click on "Security".
2. Go to "Security Groups" tab.
3. Click on "default" on the list.
4. Click "Add Connection Type".
5. On the modal, choose "CIDR/IP" on the "Connection Type".
6. Your IP address would be automatically populated on the input field.
7. Click "Authorize".

**Comment by proclamo-zz** [comment] 2018-01-31 13:01
This error happens to me when I run the code inside a new thread.

**Comment by moolyasuresh** [comment] 2019-05-16 19:40
I was able to connect after editing SG of default VPC.

**Comment by MystklFrets** [comment] 2019-06-13 02:29
@Regalcom, thank you - that worked!

**Comment by spaw6065** [comment] 2019-06-19 16:47
Thanks ghost, this worked for me
Here's what worked for me.

On the Redshift dashboard, on the left panel, click on "Security".
Go to "Security Groups" tab.
Click on "default" on the list.
Click "Add Connection Type".
On the modal, choose "CIDR/IP" on the "Connection Type".
Your IP address would be automatically populated on the input field.
Click "Authorize".

**Comment by Chloejay** [comment] 2020-06-08 07:01
Go to Security Group, select `default` user, then edit the `inbound rules`, add Redshift to `Source` from `Anywhere`, worked for me. 
=>
Redshift | TCP | 5439 | 0.0.0.0/0

**Comment by ghost** [comment] 2020-10-24 17:17
i hade the same problem go to redshift cluster modify and let public access on

**Comment by asongent** [comment] 2020-11-07 12:18
> Here's what worked for me.
> 
> 1. On the Redshift dashboard, on the left panel, click on "Security".
> 2. Go to "Security Groups" tab.
> 3. Click on "default" on the list.
> 4. Click "Add Connection Type".
> 5. On the modal, choose "CIDR/IP" on the "Connection Type".
> 6. Your IP address would be automatically populated on the input field.
> 7. Click "Authorize".



> I had the same problem as gabi-lee. I selected "No" in the "Publicly accessible" option. Consequently, despite having inbound security wide open, I was unable to connect.
> "[Amazon](500150) Error setting/closing connection"
> To fix, choose your redshift cluster and then click the "cluster" drop down.
> Select modify and then change publicly accessible.
> It took about a minute or so to take effect.

Thank you! I got connected as soon as i enabled public access. Thanks again.

**Comment by asongent** [comment] 2020-11-07 12:21
Thank you! I got connected as soon as i enabled public access. Thanks again.

**Comment by asongent** [comment] 2020-11-07 12:22
> I had the same problem as gabi-lee. I selected "No" in the "Publicly accessible" option. Consequently, despite having inbound security wide open, I was unable to connect.
> "[Amazon](500150) Error setting/closing connection"
> To fix, choose your redshift cluster and then click the "cluster" drop down.
> Select modify and then change publicly accessible.
> It took about a minute or so to take effect.

Thank you @whitsonk! I got connected as soon as i enabled public access. Thanks again.

**Comment by dineshrajnkl** [comment] 2021-07-26 10:26
Methods to follow if you come across [Amazon][500150] Error setting/closing connection:

1.Sign-in into AWS Console
2.Search in AWS console for 'Security groups' - You will get 'Security groups (ECS feature)'
3.Select Inbound rules tab < select edit inbound rules (Add Rule: Type=Redshift, Source=MyIP)
4.Also in Redshift- Open your Cluster < Actions < Modify publically accessible setting < Enable < Save Changes

Also download the latest JDBC driver (JAR) from Amazon Redshift < Clusters

Connect Redshift with SQLWorkbench/J.
